version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "next"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "next"
    versioning-strategy: "increase"
  - package-ecosystem: "npm"
    directory: "/formatter-codequality"
    schedule:
      interval: "daily"
    target-branch: "next"
    versioning-strategy: "increase"
  - package-ecosystem: "npm"
    directory: "/formatter-default"
    schedule:
      interval: "daily"
    target-branch: "next"
    versioning-strategy: "increase"
  - package-ecosystem: "npm"
    directory: "/formatter-json"
    schedule:
      interval: "daily"
    target-branch: "next"
    versioning-strategy: "increase"
  - package-ecosystem: "npm"
    directory: "/formatter-junit"
    schedule:
      interval: "daily"
    target-branch: "next"
    versioning-strategy: "increase"
  - package-ecosystem: "npm"
    directory: "/formatter-pretty"
    schedule:
      interval: "daily"
    target-branch: "next"
    versioning-strategy: "increase"
  - package-ecosystem: "npm"
    directory: "/formatter-sarif"
    schedule:
      interval: "daily"
    target-branch: "next"
    versioning-strategy: "increase"
  - package-ecosystem: "npm"
    directory: "/formatter-summarize"
    schedule:
      interval: "daily"
    target-branch: "next"
    versioning-strategy: "increase"
  - package-ecosystem: "npm"
    directory: "/formatter-template"
    schedule:
      interval: "daily"
    target-branch: "next"
    versioning-strategy: "increase"
